# Generated by Django 6.0.3 on 2026-03-11 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_question_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
